import { Product } from "@/types/product";
import { Shop } from "@/types/shop";
import { CoopPool } from "@/types/order";

// ============================================
// MOCK DATA — sẽ thay bằng API thật khi Backend sẵn sàng
// Hình ảnh lưu tại public/images/
// ============================================

export const MOCK_SEASONAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Cam Sành Hà Giang Loại 1",
    slug: "cam-sanh-ha-giang-loai-1",
    description: "Cam sành Hà Giang tươi ngon, vị ngọt thanh tự nhiên.",
    price: 45000,
    originalPrice: 50000,
    unit: "Kg",
    stock: 500,
    category: "trai-cay",
    images: ["/images/products/cam-sanh.png"],
    shopId: 1,
    shopName: "Nông trại Xanh Đà Lạt",
    shopAvatar: "/images/farms/dalat.png",
    shopLocation: "Hà Giang",
    rating: 4.8,
    soldCount: 245,
    badges: [
      { label: "Không BVTV", type: "organic" },
      { label: "Thu hoạch 15/04", type: "harvest" },
    ],
    traceability: {
      cooperative: "HTX Cam sành Hà Giang",
      regionCode: "VN-HG-0321",
      harvestDate: "15/04/2026",
      farmingMethod: "Hữu cơ",
      certification: "VietGAP",
      isOrganic: true,
      farmLocation: "Hà Giang",
    },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-14",
  },
  {
    id: 2,
    name: "Sầu Riêng Ri6 Đắk Lắk",
    slug: "sau-rieng-ri6-dak-lak",
    description: "Sầu riêng Ri6 chính gốc Đắk Lắk, cơm vàng, hạt lép.",
    price: 125000,
    unit: "Kg",
    stock: 200,
    category: "trai-cay",
    images: ["/images/products/sau-rieng.png"],
    shopId: 2,
    shopName: "Hợp tác xã Bến Tre",
    shopLocation: "Đắk Lắk",
    rating: 4.9,
    soldCount: 180,
    badges: [],
    traceability: {
      cooperative: "HTX Sầu Ri6 Đắk Lắk",
      regionCode: "VN-DL-0422",
      harvestDate: "10/04/2026",
      farmingMethod: "Canh tác hữu cơ",
      certification: "GlobalGAP",
      isOrganic: true,
      farmLocation: "Đắk Lắk",
    },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-05",
    updatedAt: "2026-03-14",
  },
  {
    id: 3,
    name: "Bưởi Da Xanh Bến Tre",
    slug: "buoi-da-xanh-ben-tre",
    description: "Bưởi da xanh vỏ mỏng ruột hồng, vị ngọt thanh.",
    price: 68000,
    unit: "Trái (~1.5kg)",
    stock: 350,
    category: "trai-cay",
    images: ["/images/products/buoi-da-xanh.png"],
    shopId: 3,
    shopName: "HTX Trái cây Bến Tre",
    shopLocation: "Bến Tre",
    rating: 4.7,
    soldCount: 320,
    badges: [{ label: "Canh tác hữu cơ", type: "organic" }],
    traceability: {
      cooperative: "HTX Trái cây Bến Tre",
      regionCode: "VN-BTRE-0421",
      harvestDate: "12/04/2026",
      farmingMethod: "Hữu cơ PGS",
      certification: "VietGAP",
      isOrganic: true,
      farmLocation: "Bến Tre",
    },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-02",
    updatedAt: "2026-03-14",
  },
  {
    id: 4,
    name: "Xoài Cát Hòa Lộc Tiền Giang",
    slug: "xoai-cat-hoa-loc-tien-giang",
    description: "Xoài cát Hòa Lộc, thịt vàng đậm, thơm nồng, vị ngọt thanh.",
    price: 95000,
    unit: "Kg",
    stock: 150,
    category: "trai-cay",
    images: ["/images/products/xoai-cat.png"],
    shopId: 4,
    shopName: "Nhà Vườn Bác Ba",
    shopLocation: "Tiền Giang",
    rating: 4.9,
    soldCount: 420,
    badges: [
      { label: "Không BVTV", type: "organic" },
      { label: "VietGAP", type: "certification" },
    ],
    traceability: {
      cooperative: "HTX Xoài Hòa Lộc",
      regionCode: "VN-TG-0520",
      harvestDate: "20/04/2026",
      farmingMethod: "Hữu cơ",
      certification: "VietGAP",
      isOrganic: true,
      farmLocation: "Tiền Giang",
    },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-14",
  },
];

export const MOCK_NEW_PRODUCTS: Product[] = [
  {
    id: 5,
    name: "Cá Tầm Sapa Tươi Sống",
    slug: "ca-tam-sapa-tuoi-song",
    description: "Cá tầm Sapa được nuôi trong nước lạnh tự nhiên.",
    price: 280000,
    unit: "Kg",
    stock: 50,
    category: "thuy-hai-san",
    images: ["/images/products/ca-tam.png"],
    shopId: 5,
    shopName: "Trang trại Sapa",
    shopLocation: "Lào Cai",
    rating: 4.6,
    soldCount: 78,
    badges: [],
    traceability: { cooperative: "", regionCode: "VN-LC-0101", harvestDate: "14/03/2026", farmingMethod: "Nuôi nước lạnh", certification: "", isOrganic: false, farmLocation: "Sapa, Lào Cai" },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-10",
    updatedAt: "2026-03-14",
  },
  {
    id: 6,
    name: "Nấm Mối Đen Hữu Cơ",
    slug: "nam-moi-den-huu-co",
    description: "Nấm mối đen hữu cơ, giàu dinh dưỡng.",
    price: 55000,
    unit: "Khay 200g",
    stock: 120,
    category: "rau-cu",
    images: ["/images/products/nam-moi.png"],
    shopId: 1,
    shopName: "Nông trại Xanh Đà Lạt",
    shopLocation: "Đà Lạt",
    rating: 4.8,
    soldCount: 95,
    badges: [],
    traceability: { cooperative: "", regionCode: "VN-DL-0205", harvestDate: "13/03/2026", farmingMethod: "Hữu cơ", certification: "", isOrganic: true, farmLocation: "Đà Lạt" },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-08",
    updatedAt: "2026-03-14",
  },
  {
    id: 7,
    name: "Thịt Bò Tơ Củ Chi",
    slug: "thit-bo-to-cu-chi",
    description: "Thịt bò tơ Củ Chi tươi ngon, nguồn gốc rõ ràng.",
    price: 245000,
    unit: "Kg",
    stock: 80,
    category: "thit-trung",
    images: ["/images/products/thit-bo.png"],
    shopId: 6,
    shopName: "Trang trại Củ Chi",
    shopLocation: "TP.HCM",
    rating: 4.5,
    soldCount: 150,
    badges: [],
    traceability: { cooperative: "", regionCode: "VN-HCM-CC01", harvestDate: "14/03/2026", farmingMethod: "Chăn nuôi tự nhiên", certification: "", isOrganic: false, farmLocation: "Củ Chi, TP.HCM" },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-12",
    updatedAt: "2026-03-14",
  },
  {
    id: 8,
    name: "Rau Mầm Đá Hà Giang",
    slug: "rau-mam-da-ha-giang",
    description: "Rau mầm đá đặc sản Hà Giang, giàu khoáng chất.",
    price: 35000,
    unit: "Kg",
    stock: 200,
    category: "rau-cu",
    images: ["/images/products/rau-mam.png"],
    shopId: 7,
    shopName: "Hợp tác xã Hà Giang",
    shopLocation: "Hà Giang",
    rating: 4.7,
    soldCount: 60,
    badges: [],
    traceability: { cooperative: "", regionCode: "VN-HG-0101", harvestDate: "13/03/2026", farmingMethod: "Tự nhiên", certification: "", isOrganic: true, farmLocation: "Hà Giang" },
    seasonStatus: "IN_SEASON",
    createdAt: "2026-03-11",
    updatedAt: "2026-03-14",
  },
];

export const MOCK_SHOPS: Shop[] = [
  {
    id: 1,
    name: "Nông trại Xanh Đà Lạt",
    slug: "nong-trai-xanh-da-lat",
    avatar: "/images/farms/dalat.png",
    coverImage: "",
    location: "Lâm Đồng",
    province: "Lâm Đồng",
    story: "",
    yearsOfExperience: 15,
    farmArea: "5 hecta",
    rating: 4.8,
    reviewCount: 120,
    productCount: 12,
    soldCount: 1500,
    certifications: ["VietGAP"],
    contactAddress: "Đà Lạt, Lâm Đồng",
    openHours: "07:00 - 18:00",
    galleryImages: [],
    createdAt: "2020-01-01",
  },
  {
    id: 2,
    name: "Hợp tác xã Bến Tre",
    slug: "hop-tac-xa-ben-tre",
    avatar: "/images/farms/bentre.png",
    coverImage: "",
    location: "Bến Tre",
    province: "Bến Tre",
    story: "",
    yearsOfExperience: 8,
    farmArea: "3 hecta",
    rating: 4.9,
    reviewCount: 85,
    productCount: 8,
    soldCount: 950,
    certifications: ["VietGAP", "OCOP 4 sao"],
    contactAddress: "TP. Bến Tre, Tỉnh Bến Tre",
    openHours: "07:00 - 18:00",
    galleryImages: [],
    createdAt: "2018-06-15",
  },
  {
    id: 3,
    name: "Vườn Cây Ăn Trái Cần Thơ",
    slug: "vuon-cay-an-trai-can-tho",
    avatar: "/images/farms/cantho.png",
    coverImage: "",
    location: "Cần Thơ",
    province: "Cần Thơ",
    story: "",
    yearsOfExperience: 20,
    farmArea: "8 hecta",
    rating: 4.7,
    reviewCount: 200,
    productCount: 15,
    soldCount: 3200,
    certifications: ["GlobalGAP"],
    contactAddress: "Cần Thơ",
    openHours: "06:30 - 17:30",
    galleryImages: [],
    createdAt: "2006-03-01",
  },
];

export const MOCK_COOP_POOL: CoopPool = {
  id: 1,
  productName: "Cam sành Vĩnh Long - Bến Tre",
  productImage: "/images/products/cam-sanh.png",
  targetQuantity: 1000,
  currentQuantity: 650,
  pricePerUnit: 35000,
  region: "ĐBSCL",
  deadline: "2026-03-17T00:00:00",
  participantCount: 12,
  status: "OPEN",
  contributions: [],
};

// Flash deals — giá sốc hôm nay
export const MOCK_FLASH_DEALS: Product[] = [
  {
    id: 101, name: "Cam Sành Hà Giang", slug: "cam-sanh-flash",
    description: "Deal sốc", price: 29000, originalPrice: 50000,
    unit: "Kg", stock: 30, category: "trai-cay",
    images: ["/images/products/cam-sanh.png"],
    shopId: 1, shopName: "Nông trại Xanh", shopAvatar: "/images/farms/dalat.png",
    shopLocation: "Hà Giang", rating: 4.8, soldCount: 180,
    badges: [], traceability: { cooperative: "", regionCode: "", harvestDate: "",
      farmingMethod: "", certification: "", isOrganic: false, farmLocation: "" },
    seasonStatus: "IN_SEASON", createdAt: "2026-03-15", updatedAt: "2026-03-15",
  },
  {
    id: 102, name: "Sầu Riêng Ri6", slug: "sau-rieng-flash",
    description: "Deal sốc", price: 89000, originalPrice: 150000,
    unit: "Kg", stock: 20, category: "trai-cay",
    images: ["/images/products/sau-rieng.png"],
    shopId: 2, shopName: "Vườn Bến Tre", shopAvatar: "/images/farms/bentre.png",
    shopLocation: "Đắk Lắk", rating: 4.9, soldCount: 320,
    badges: [], traceability: { cooperative: "", regionCode: "", harvestDate: "",
      farmingMethod: "", certification: "", isOrganic: false, farmLocation: "" },
    seasonStatus: "IN_SEASON", createdAt: "2026-03-15", updatedAt: "2026-03-15",
  },
  {
    id: 103, name: "Bưởi Da Xanh Bến Tre", slug: "buoi-flash",
    description: "Deal sốc", price: 35000, originalPrice: 65000,
    unit: "Trái", stock: 50, category: "trai-cay",
    images: ["/images/products/buoi-da-xanh.png"],
    shopId: 2, shopName: "Vườn Bến Tre", shopAvatar: "/images/farms/bentre.png",
    shopLocation: "Bến Tre", rating: 4.7, soldCount: 450,
    badges: [], traceability: { cooperative: "", regionCode: "", harvestDate: "",
      farmingMethod: "", certification: "", isOrganic: false, farmLocation: "" },
    seasonStatus: "IN_SEASON", createdAt: "2026-03-15", updatedAt: "2026-03-15",
  },
  {
    id: 104, name: "Xoài Cát Hòa Lộc", slug: "xoai-flash",
    description: "Deal sốc", price: 55000, originalPrice: 90000,
    unit: "Kg", stock: 40, category: "trai-cay",
    images: ["/images/products/xoai-cat.png"],
    shopId: 3, shopName: "Vườn Cần Thơ", shopAvatar: "/images/farms/cantho.png",
    shopLocation: "Tiền Giang", rating: 4.6, soldCount: 210,
    badges: [], traceability: { cooperative: "", regionCode: "", harvestDate: "",
      farmingMethod: "", certification: "", isOrganic: false, farmLocation: "" },
    seasonStatus: "IN_SEASON", createdAt: "2026-03-15", updatedAt: "2026-03-15",
  },
  {
    id: 105, name: "Nấm Mối Tây Ninh", slug: "nam-flash",
    description: "Deal sốc", price: 65000, originalPrice: 120000,
    unit: "Kg", stock: 15, category: "nam",
    images: ["/images/products/nam-moi.png"],
    shopId: 1, shopName: "Nông trại Xanh", shopAvatar: "/images/farms/dalat.png",
    shopLocation: "Tây Ninh", rating: 4.5, soldCount: 95,
    badges: [], traceability: { cooperative: "", regionCode: "", harvestDate: "",
      farmingMethod: "", certification: "", isOrganic: false, farmLocation: "" },
    seasonStatus: "IN_SEASON", createdAt: "2026-03-15", updatedAt: "2026-03-15",
  },
  {
    id: 106, name: "Rau Mầm Đà Lạt", slug: "rau-mam-flash",
    description: "Deal sốc", price: 18000, originalPrice: 35000,
    unit: "Hộp", stock: 60, category: "rau-cu",
    images: ["/images/products/rau-mam.png"],
    shopId: 1, shopName: "Nông trại Xanh", shopAvatar: "/images/farms/dalat.png",
    shopLocation: "Đà Lạt", rating: 4.8, soldCount: 530,
    badges: [], traceability: { cooperative: "", regionCode: "", harvestDate: "",
      farmingMethod: "", certification: "", isOrganic: false, farmLocation: "" },
    seasonStatus: "IN_SEASON", createdAt: "2026-03-15", updatedAt: "2026-03-15",
  },
];
