/**
 * API Cart Service — Khớp BE CartController (updated)
 *
 * BE Endpoints:
 *   POST   /api/cart/items        → Thêm sản phẩm vào giỏ { productId (UUID), quantity (BigDecimal) }
 *   GET    /api/cart              → Lấy giỏ hàng
 *   PUT    /api/cart/items/{id}   → Cập nhật số lượng { quantity }
 *   DELETE /api/cart/items/{id}   → Xóa item khỏi giỏ
 *   POST   /api/cart/merge        → Merge giỏ guest → user (sau khi login)
 *
 * Headers:
 *   Guest-Session-Id: UUID — cho user chưa login (auto-generated by Axios interceptor)
 *
 * BE CartResponse: { id, guestSessionId, userId, items: CartItemResponse[] }
 * BE CartItemResponse: { id, productId, productName, quantity, pricePerUnit }
 */
import api from "../api";
import type { ICartService, CartItem } from "../types";

export const apiCartService: ICartService = {
  async getCart(): Promise<CartItem[]> {
    try {
      const res = await api.get("/api/cart");
      const data = res.data.data || res.data;
      // Normalize BE CartItemResponse → FE CartItem
      return (data.items || data || []).map((item: Record<string, unknown>) => ({
        id: String(item.id),
        productId: String(item.productId || ""),
        productName: (item.productName || "") as string,
        quantity: Number(item.quantity || 0),
        pricePerUnit: Number(item.pricePerUnit || 0),
      }));
    } catch {
      return [];
    }
  },

  async addItem(productId: string, quantity: number): Promise<void> {
    await api.post("/api/cart/items", {
      productId,
      quantity,
    });
  },

  async updateItem(itemId: string, quantity: number): Promise<void> {
    await api.put(`/api/cart/items/${itemId}`, {
      quantity,
    });
  },

  async removeItem(itemId: string): Promise<void> {
    try {
      await api.delete(`/api/cart/items/${itemId}`);
    } catch {
      // Silently ignore — item might not exist
    }
  },

  async clearCart(): Promise<void> {
    const items = await this.getCart();
    await Promise.all(items.map((item) => this.removeItem(item.id)));
  },

  async getItemCount(): Promise<number> {
    const items = await this.getCart();
    return items.reduce((sum, item) => sum + item.quantity, 0);
  },
};

/**
 * Merge guest cart → user cart (gọi sau khi login)
 * Cần Guest-Session-Id header — đã tự động attach bởi Axios interceptor
 */
export async function mergeGuestCart(): Promise<void> {
  const guestSessionId = localStorage.getItem("guest_session_id");
  if (!guestSessionId) return;
  try {
    await api.post("/api/cart/merge", null, {
      headers: { "Guest-Session-Id": guestSessionId },
    });
    // Sau khi merge thành công → xóa guest session
    localStorage.removeItem("guest_session_id");
  } catch {
    // Silently fail — guest cart might be empty
  }
}
