/**
 * API Cart Service — Khớp BE CartController (updated)
 *
 * BE Endpoints:
 *   POST   /api/cart/items        → Thêm sản phẩm vào giỏ { productId (UUID), quantity (BigDecimal) }
 *   GET    /api/cart              → Lấy giỏ hàng
 *   PUT    /api/cart/items/{id}   → Cập nhật số lượng { quantity }
 *   DELETE /api/cart/items/{id}   → Xóa item khỏi giỏ
 *   POST   /api/cart/merge        → Merge giỏ guest → user (sau khi login)
 *
 * Headers:
 *   Guest-Session-Id: UUID — cho user chưa login (auto-generated by Axios interceptor)
 *
 * BE CartResponse: { id, guestSessionId, userId, items: CartItemResponse[] }
 * BE CartItemResponse: { id, productId, productName, quantity, pricePerUnit }
 */
import api from "../api";
import type { ICartService, CartItem } from "../types";

export const apiCartService: ICartService = {
  async getCart(): Promise<CartItem[]> {
    try {
      const res = await api.get("/api/cart");
      const data = res.data.data || res.data;
      // Normalize BE CartItemResponse → FE CartItem
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      return (data.items || data || []).map((item: any) => ({
        id: String(item.id),
        quantity: Number(item.quantity || 0),
        product: {
          id: String(item.product_id || ""),
          name: (item.product_name || "") as string,
          price_per_unit: Number(item.price_per_unit || 0),
          images: item.image_url ? [item.image_url] : [],
          shop: { name: (item.shop_name || "") as string },
        }
      }));
    } catch {
      return [];
    }
  },

  async addItem(productId: string, quantity: number): Promise<void> {
    await api.post("/api/cart/items", {
      product_id: productId,
      quantity,
    });
    if (typeof window !== "undefined") window.dispatchEvent(new Event("cartUpdated"));
  },

  async updateItem(itemId: string, quantity: number): Promise<void> {
    await api.put(`/api/cart/items/${itemId}`, {
      quantity,
    });
    if (typeof window !== "undefined") window.dispatchEvent(new Event("cartUpdated"));
  },

  async removeItem(itemId: string): Promise<void> {
    try {
      await api.delete(`/api/cart/items/${itemId}`);
      if (typeof window !== "undefined") window.dispatchEvent(new Event("cartUpdated"));
    } catch {
      // Silently ignore — item might not exist
    }
  },

  async clearCart(): Promise<void> {
    const items = await this.getCart();
    await Promise.all(items.map((item) => this.removeItem(item.id)));
    if (typeof window !== "undefined") window.dispatchEvent(new Event("cartUpdated"));
  },

  async getItemCount(): Promise<number> {
    const items = await this.getCart();
    return items.reduce((sum, item) => sum + item.quantity, 0);
  },
};

/**
 * Merge guest cart → user cart (gọi sau khi login)
 * Cần Guest-Session-Id header — đã tự động attach bởi Axios interceptor
 */
export async function mergeGuestCart(): Promise<void> {
  const guestSessionId = localStorage.getItem("guest_session_id");
  if (!guestSessionId) return;
  try {
    await api.post("/api/cart/merge", null, {
      headers: { "Guest-Session-Id": guestSessionId },
    });
    // Sau khi merge thành công → xóa guest session
    localStorage.removeItem("guest_session_id");
  } catch {
    // Silently fail — guest cart might be empty
  }
}
